### ISSUE TITLE
imageHD fawe related error

### ISSUE THREAD

**Issue by andrewjunggg** [SBPrime/MCPainter#6]
I'm using FAWE as my world edit, and can't use ImageHD command in my server. The console gives an error like this. I hope this will help on future update.
```
[10:21:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mcpainter' in plugin MCPainter v1.0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-624]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.regions.Region.getMinimumPoint()Lcom/sk89q/worldedit/Vector;
        at org.primesoft.mcpainter.worldEdit.WorldEditWrapper.getSelection(WorldEditWrapper.java:91) ~[?:?]
        at org.primesoft.mcpainter.commands.HdImageCommand.Execute(HdImageCommand.java:81) ~[?:?]
        at org.primesoft.mcpainter.MCPainterMain.doHdImage(MCPainterMain.java:694) ~[?:?]
        at org.primesoft.mcpainter.MCPainterMain.onCommand(MCPainterMain.java:282) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-624]
        ... 15 more
```

**Comment by SBPrime** [comment]
That version of WorldEdit is not supported. The plugin failed because of API incompatibility.
